### ISSUE TITLE
/tmp file not found and UnicodeDecodeError

### ISSUE THREAD

**Issue by YiHuang108** [Thinklab-SJTU/Bench2DriveZoo#11]
I've tried reconverting the encoding, but to no avail.

Also, I don't know why the code is trying to find the /tmp files. I have been able to run the training command with VAD.  

Looking forward to your reply.

the return is:

```
Traceback (most recent call last):
  File "./adzoo/vad/test.py", line 278, in <module>
    main()
  File "./adzoo/vad/test.py", line 122, in main
    cfg = Config.fromfile(args.config)
  File "Bench2DriveZoo/mmcv/utils/config.py", line 332, in fromfile
    use_predefined_variables)
  File "Bench2DriveZoo/mmcv/utils/config.py", line 196, in _file2dict
    temp_config_file.name)
  File "Bench2DriveZoo/mmcv/utils/config.py", line 120, in _substitute_predefined_vars
    config_file = f.read()
  File "/home/miniconda3/envs/my_python/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc8 in position 88: invalid continuation byte
Exception ignored in: <function _TemporaryFileCloser.__del__ at 0x7bb5fe430680>
Traceback (most recent call last):
  File "/home/miniconda3/envs/my_python/lib/python3.7/tempfile.py", line 448, in __del__
    self.close()
  File "/home/miniconda3/envs/my_python/lib/python3.7/tempfile.py", line 444, in close
    unlink(self.name)
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpbdmyj1zj/tmpx7un6pqw.py'
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 104200) of binary: /home/miniconda3/envs/my_python/bin/python

```

**Comment by jiaxiaosong1002** [comment]
@YiHuang108 The actual error is this line: “UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc8 in position 88: invalid continuation byte”.

Your config might have  some illegal characters.

**Comment by YiHuang108** [comment]
Problem solved. Thank you very much for your help.
