### ISSUE TITLE
An error occurred while compiling mmcv

### ISSUE THREAD

**Issue by kennycZhang** [Thinklab-SJTU/Bench2DriveZoo#13]
Hello, I cannot compile mmcv successfully, I would like to ask you about the gcc and torch versions you use. 
I used 
gcc:9.4
torchaudio 2.0.2+cu118
torchmetrics 0.11.4
torchvision 0.15.2+cu118

**Comment by jiaxiaosong1002** [comment]
@kennycZhang We use gcc 9.4 + cu118 as well.

**Comment by AvinsWang** [comment]
@kennycZhang  I faced same error to you, How did you solve the problem?

```
torch                     2.4.0+cu118
torchaudio                2.4.0+cu118
torchmetrics              0.11.4
torchvision               0.19.0+cu118
```

```
export PATH=/usr/bin/gcc/bin:$PATH
export CUDA_HOME=/root/miniconda3/envs/b2d_zoo
```


```
[23/82] c++ -MMD -MF /data/user/code/bev/Bench2DriveZoo/build/temp.linux-x86_64-cpython-38/mmcv/ops/csrc/pytorch/cpu/nms_rotated.o.d -pthread -B /root/miniconda3/envs/b2d_zoo/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -DMMCV_WITH_CUDA -I/data/user/code/bev/Bench2DriveZoo/mmcv/ops/csrc/common -
I/data/user/code/bev/Bench2DriveZoo/mmcv/ops/csrc/common/cuda -I/root/miniconda3/envs/b2d_zoo/lib/python3.8/site-packages/torch/include -I/root/miniconda3/envs/b2d_zoo/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -I/root/miniconda3/envs/b2d_zoo/lib/python3.8/site-packages/torch/include/TH -I/root/miniconda3/envs/b2d_zoo/lib/python3.8/site
-packages/torch/include/THC -I/root/miniconda3/envs/b2d_zoo/include -I/root/miniconda3/envs/b2d_zoo/include/python3.8 -c -c /data/user/code/bev/Bench2DriveZoo/mmcv/ops/csrc/pytorch/cpu/nms_rotated.cpp -o /data/user/code/bev/Bench2DriveZoo/build/temp.linux-x86_64-cpython-38/mmcv/ops/csrc/pytorch/cpu/nms_rotated.o -std=c++17 -DTORCH_API_INCLUDE_EXTENSION_H '
-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_ext -D_GLIBCXX_USE_CXX11_ABI=0
    cc1plus: warning: command line option _-Wstrict-prototypes_ is valid for C/ObjC but not for C++
    In file included from /root/miniconda3/envs/b2d_zoo/lib/python3.8/site-packages/torch/include/ATen/ATen.h:11,
                     from /root/miniconda3/envs/b2d_zoo/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/types.h:3,
                     from /root/miniconda3/envs/b2d_zoo/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader_options.h:4,
                     from /root/miniconda3/envs/b2d_zoo/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/base.h:3,
                     from /root/miniconda3/envs/b2d_zoo/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/stateful.h:4,
                     from /root/miniconda3/envs/b2d_zoo/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader.h:3,
                     from /root/miniconda3/envs/b2d_zoo/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/data.h:3,
                     from /root/miniconda3/envs/b2d_zoo/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/all.h:9,
                     from /root/miniconda3/envs/b2d_zoo/lib/python3.8/site-packages/torch/include/torch/extension.h:5,
                     from /data/user/code/bev/Bench2DriveZoo/mmcv/ops/csrc/common/pytorch_cpp_helper.hpp:3,
                     from /data/user/code/bev/Bench2DriveZoo/mmcv/ops/csrc/pytorch/cpu/nms_rotated.cpp:5:
    /data/user/code/bev/Bench2DriveZoo/mmcv/ops/csrc/pytorch/cpu/nms_rotated.cpp: In lambda function:
    /data/user/code/bev/Bench2DriveZoo/mmcv/ops/csrc/pytorch/cpu/nms_rotated.cpp:62:40: warning: _at::DeprecatedTypeProperties& at::Tensor::type() const_ is deprecated: Tensor.type() is deprecated. Instead use Tensor.options(), which in many cases (e.g. in a constructor) is a drop-in replacement. If you were using data from type(), that is now available from
 Tensor itself, so instead of tensor.type().scalar_type(), use tensor.scalar_type() instead and instead of tensor.type().backend() use tensor.device(). [-Wdeprecated-declarations]
       62 |   AT_DISPATCH_FLOATING_TYPES(dets.type(), "nms_rotated", [&] {
          |                                        ^
    /root/miniconda3/envs/b2d_zoo/lib/python3.8/site-packages/torch/include/ATen/Dispatch.h:215:28: note: in definition of macro _AT_DISPATCH_SWITCH_
      215 |     const auto& the_type = TYPE;                                            \
          |                            ^~~~
    /data/user/code/bev/Bench2DriveZoo/mmcv/ops/csrc/pytorch/cpu/nms_rotated.cpp:62:3: note: in expansion of macro _AT_DISPATCH_FLOATING_TYPES_
       62 |   AT_DISPATCH_FLOATING_TYPES(dets.type(), "nms_rotated", [&] {
          |   ^~~~~~~~~~~~~~~~~~~~~~~~~~
    In file included from /root/miniconda3/envs/b2d_zoo/lib/python3.8/site-packages/torch/include/ATen/core/Tensor.h:3,
                     from /root/miniconda3/envs/b2d_zoo/lib/python3.8/site-packages/torch/include/ATen/Tensor.h:3,
                     from /root/miniconda3/envs/b2d_zoo/lib/python3.8/site-packages/torch/include/torch/csrc/autograd/function_hook.h:3,
                     from /root/miniconda3/envs/b2d_zoo/lib/python3.8/site-packages/torch/include/torch/csrc/autograd/cpp_hook.h:2,
                     from /root/miniconda3/envs/b2d_zoo/lib/python3.8/site-packages/torch/include/torch/csrc/autograd/variable.h:6,
                     from /root/miniconda3/envs/b2d_zoo/lib/python3.8/site-packages/torch/include/torch/csrc/autograd/autograd.h:3,
                     from /root/miniconda3/envs/b2d_zoo/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/autograd.h:3,
                     from /root/miniconda3/envs/b2d_zoo/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/all.h:7,
                     from /root/miniconda3/envs/b2d_zoo/lib/python3.8/site-packages/torch/include/torch/extension.h:5,
                     from /data/user/code/bev/Bench2DriveZoo/mmcv/ops/csrc/common/pytorch_cpp_helper.hpp:3,
                     from /data/user/code/bev/Bench2DriveZoo/mmcv/ops/csrc/pytorch/cpu/nms_rotated.cpp:5:
    /root/miniconda3/envs/b2d_zoo/lib/python3.8/site-packages/torch/include/ATen/core/TensorBody.h:225:30: note: declared here
      225 |   DeprecatedTypeProperties & type() const {
          |                              ^~~~
    In file included from /root/miniconda3/envs/b2d_zoo/lib/python3.8/site-packages/torch/include/ATen/ATen.h:11,
                     from /root/miniconda3/envs/b2d_zoo/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/types.h:3,
                     from /root/miniconda3/envs/b2d_zoo/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader_options.h:4,
                     from /root/miniconda3/envs/b2d_zoo/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/base.h:3,
                     from /root/miniconda3/envs/b2d_zoo/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader/stateful.h:4,
                     from /root/miniconda3/envs/b2d_zoo/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/data/dataloader.h:3,
                     from /root/miniconda3/envs/b2d_zoo/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/data.h:3,
                     from /root/miniconda3/envs/b2d_zoo/lib/python3.8/site-packages/torch/include/torch/csrc/api/include/torch/all.h:9,
                     from /root/miniconda3/envs/b2d_zoo/lib/python3.8/site-packages/torch/include/torch/extension.h:5,
                     from /data/user/code/bev/Bench2DriveZoo/mmcv/ops/csrc/common/pytorch_cpp_helper.hpp:3,
                     from /data/user/code/bev/Bench2DriveZoo/mmcv/ops/csrc/pytorch/cpu/nms_rotated.cpp:5:
    /root/miniconda3/envs/b2d_zoo/lib/python3.8/site-packages/torch/include/ATen/Dispatch.h:218:56: warning: _c10::ScalarType detail::scalar_type(const at::DeprecatedTypeProperties&)_ is deprecated: passing at::DeprecatedTypeProperties to an AT_DISPATCH macro is deprecated, pass an at::ScalarType instead [-Wdeprecated-declarations]
      218 |     at::ScalarType _st = ::detail::scalar_type(the_type);
/root/miniconda3/envs/b2d_zoo/lib/python3.8/site-packages/torch/include/ATen/Dispatch.h:237:3: note: in expansion of macro _AT_DISPATCH_SWITCH_
      237 |   AT_DISPATCH_SWITCH(TYPE, NAME, AT_DISPATCH_CASE_FLOATING_TYPES(__VA_ARGS__))
          |   ^~~~~~~~~~~~~~~~~~
    /data/user/code/bev/Bench2DriveZoo/mmcv/ops/csrc/pytorch/cpu/nms_rotated.cpp:62:3: note: in expansion of macro _AT_DISPATCH_FLOATING_TYPES_
       62 |   AT_DISPATCH_FLOATING_TYPES(dets.type(), "nms_rotated", [&] {
          |   ^~~~~~~~~~~~~~~~~~~~~~~~~~
    /root/miniconda3/envs/b2d_zoo/lib/python3.8/site-packages/torch/include/ATen/Dispatch.h:109:23: note: declared here
      109 | inline at::ScalarType scalar_type(const at::DeprecatedTypeProperties& t) {
          |                       ^~~~~~~~~~~
    /root/miniconda3/envs/b2d_zoo/lib/python3.8/site-packages/torch/include/ATen/Dispatch.h:218:56: warning: _c10::ScalarType detail::scalar_type(const at::DeprecatedTypeProperties&)_ is deprecated: passing at::DeprecatedTypeProperties to an AT_DISPATCH macro is deprecated, pass an at::ScalarType instead [-Wdeprecated-declarations]
      218 |     at::ScalarType _st = ::detail::scalar_type(the_type);                   \
          |                                                        ^
    /root/miniconda3/envs/b2d_zoo/lib/python3.8/site-packages/torch/include/ATen/Dispatch.h:237:3: note: in expansion of macro _AT_DISPATCH_SWITCH_
      237 |   AT_DISPATCH_SWITCH(TYPE, NAME, AT_DISPATCH_CASE_FLOATING_TYPES(__VA_ARGS__))
          |   ^~~~~~~~~~~~~~~~~~
    /data/user/code/bev/Bench2DriveZoo/mmcv/ops/csrc/pytorch/cpu/nms_rotated.cpp:62:3: note: in expansion of macro _AT_DISPATCH_FLOATING_TYPES_
       62 |   AT_DISPATCH_FLOATING_TYPES(dets.type(), "nms_rotated", [&] {
          |   ^~~~~~~~~~~~~~~~~~~~~~~~~~
    /root/miniconda3/envs/b2d_zoo/lib/python3.8/site-packages/torch/include/ATen/Dispatch.h:109:23: note: declared here
      109 | inline at::ScalarType scalar_type(const at::DeprecatedTypeProperties& t) {
          |                       ^~~~~~~~~~~
    ninja: build stopped: subcommand failed.
    Traceback (most recent call last):
      File "/root/miniconda3/envs/b2d_zoo/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 2105, in _run_ninja_build
        subprocess.run(
      File "/root/miniconda3/envs/b2d_zoo/lib/python3.8/subprocess.py", line 516, in run
        raise CalledProcessError(retcode, process.args,
    subprocess.CalledProcessError: Command '['ninja', '-v', '-j', '15']' returned non-zero exit status 1.

    The above exception was the direct cause of the following exception:

    Traceback (most recent call last):
      File "<string>", line 2, in <module>
      File "<pip-setuptools-caller>", line 34, in <module>
      File "/data/user/code/bev/Bench2DriveZoo/setup.py", line 181, in <module>
        setup(
      File "/root/miniconda3/envs/b2d_zoo/lib/python3.8/site-packages/setuptools/__init__.py", line 108, in setup
        return distutils.core.setup(**attrs)
      File "/root/miniconda3/envs/b2d_zoo/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 184, in setup
        return run_commands(dist)
      File "/root/miniconda3/envs/b2d_zoo/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 200, in run_commands
        dist.run_commands()
      File "/root/miniconda3/envs/b2d_zoo/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 970, in run_commands
        self.run_command(cmd)
      File "/root/miniconda3/envs/b2d_zoo/lib/python3.8/site-packages/setuptools/dist.py", line 945, in run_command
        super().run_command(command)
      File "/root/miniconda3/envs/b2d_zoo/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 989, in run_command
        cmd_obj.run()
      File "/root/miniconda3/envs/b2d_zoo/lib/python3.8/site-packages/setuptools/command/develop.py", line 36, in run
        self.install_for_development()
      File "/root/miniconda3/envs/b2d_zoo/lib/python3.8/site-packages/setuptools/command/develop.py", line 113, in install_for_development
        self.run_command('build_ext')
      File "/root/miniconda3/envs/b2d_zoo/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 316, in run_command
        self.distribution.run_command(command)
      File "/root/miniconda3/envs/b2d_zoo/lib/python3.8/site-packages/setuptools/dist.py", line 945, in run_command
        super().run_command(command)
      File "/root/miniconda3/envs/b2d_zoo/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 989, in run_command
        cmd_obj.run()
      File "/root/miniconda3/envs/b2d_zoo/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 93, in run
        _build_ext.run(self)
      File "/root/miniconda3/envs/b2d_zoo/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 359, in run
        self.build_extensions()
      File "/root/miniconda3/envs/b2d_zoo/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 866, in build_extensions
        build_ext.build_extensions(self)
      File "/root/miniconda3/envs/b2d_zoo/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 479, in build_extensions
        self._build_extensions_serial()
      File "/root/miniconda3/envs/b2d_zoo/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 505, in _build_extensions_serial
self.build_extension(ext)
      File "/root/miniconda3/envs/b2d_zoo/lib/python3.8/site-packages/setuptools/command/build_ext.py", line 254, in build_extension
        _build_ext.build_extension(self, ext)
      File "/root/miniconda3/envs/b2d_zoo/lib/python3.8/site-packages/Cython/Distutils/build_ext.py", line 135, in build_extension
        super(build_ext, self).build_extension(ext)
      File "/root/miniconda3/envs/b2d_zoo/lib/python3.8/site-packages/setuptools/_distutils/command/build_ext.py", line 560, in build_extension
        objects = self.compiler.compile(
      File "/root/miniconda3/envs/b2d_zoo/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 679, in unix_wrap_ninja_compile
        _write_ninja_file_and_compile_objects(
      File "/root/miniconda3/envs/b2d_zoo/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 1785, in _write_ninja_file_and_compile_objects
        _run_ninja_build(
      File "/root/miniconda3/envs/b2d_zoo/lib/python3.8/site-packages/torch/utils/cpp_extension.py", line 2121, in _run_ninja_build
        raise RuntimeError(message) from e
    RuntimeError: Error compiling objects for extension
    error: subprocess-exited-with-error

    _ python setup.py develop did not run successfully.
    _ exit code: 1
    __> See above for output.

    note: This error originates from a subprocess, and is likely not a problem with pip.
    full command: /root/miniconda3/envs/b2d_zoo/bin/python -c '
    exec(compile('"'"''"'"''"'"'
    # This is <pip-setuptools-caller> -- a caller that pip uses to run setup.py
    #
    # - It imports setuptools before invoking setup.py, to enable projects that directly
    #   import from `distutils.core` to work with newer packaging standards.
    # - It provides a clear error message when setuptools is not installed.
    # - It sets `sys.argv[0]` to the underlying `setup.py`, when invoking `setup.py` so
    #   setuptools doesn'"'"'t think the script is `-c`. This avoids the following warning:
    #     manifest_maker: standard file '"'"'-c'"'"' not found".
    # - It generates a shim setup.py, for handling setup.cfg-only projects.
    import os, sys, tokenize

    try:
        import setuptools
    except ImportError as error:
        print(
            "ERROR: Can not execute `setup.py` since setuptools is not available in "
            "the build environment.",
            file=sys.stderr,
        )
        sys.exit(1)

    __file__ = %r
    sys.argv[0] = __file__

    if os.path.exists(__file__):
        filename = __file__
        with tokenize.open(__file__) as f:
            setup_py_code = f.read()
    else:
        filename = "<auto-generated setuptools caller>"
        setup_py_code = "from setuptools import setup; setup()"

    exec(compile(setup_py_code, filename, "exec"))
    '"'"''"'"''"'"' % ('"'"'/data/user/code/bev/Bench2DriveZoo/setup.py'"'"',), "<pip-setuptools-caller>", "exec"))' develop --no-deps
    cwd: /data/user/code/bev/Bench2DriveZoo/
error: subprocess-exited-with-error

_ python setup.py develop did not run successfully.
_ exit code: 1
__> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by emadaghajanzadeh** [comment]
Hi, thanks for the great work!

I encountered a similar issue when installing `mmcv` with `pip install -v -e .` inside a Docker container.  
Here was my setup:
- **Docker Image**: `nvidia/cuda:11.8`
- **Ubuntu**: 22.04
- **CUDA**: 11.8
- **GCC**: 9.4
- **Python**: 3.8

**Error log**:
subprocess.CalledProcessError: Command '['ninja', '-v', '-j', '79']' returned non-zero exit status 1.

**Solution**:  
In my case, I was installing it inside a Docker CUDA image. After setting up Python 3.8, I had forgotten to install `python3.8-dev`.  This package provides the necessary header files and static libraries required for building C extensions and interfacing with C/C++ libraries.  
Installing `python3.8-dev` resolved the issue. So, make sure to install it as well!

**Comment by jayyoung0802** [comment]
Hi @emadaghajanzadeh, can you provide more details about the output log?

**Comment by emadaghajanzadeh** [comment]
Please see it below:
<details>
<summary><code>Click to expand error log</code></summary>

```text

[79/89] /usr/local/cuda/bin/nvcc --generate-dependencies-with-compile --dependency-output /workspace/Bench2DriveZoo/build/temp.linux-x86_64-3.8/mmcv/ops/csrc/pytorch/cuda/nms_rotated_cuda.o.d -DMMCV_WITH_CUDA -I/workspace/Bench2DriveZoo/mmcv/ops/csrc/common -I/workspace/Bench2DriveZoo/mmcv/ops/csrc/common/cuda -I/usr/local/lib/python3.8/dist-packages/torch/include -I/usr/local/lib/python3.8/dist-packages/torch/include/torch/csrc/api/include -I/usr/local/lib/python3.8/dist-packages/torch/include/TH -I/usr/local/lib/python3.8/dist-packages/torch/include/THC -I/usr/local/cuda/include -I/usr/include/python3.8 -c -c /workspace/Bench2DriveZoo/mmcv/ops/csrc/pytorch/cuda/nms_rotated_cuda.cu -o /workspace/Bench2DriveZoo/build/temp.linux-x86_64-3.8/mmcv/ops/csrc/pytorch/cuda/nms_rotated_cuda.o -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__ --expt-relaxed-constexpr --compiler-options ''"'"'-fPIC'"'"'' -std=c++17 -DTORCH_API_INCLUDE_EXTENSION_H '-DPYBIND11_COMPILER_TYPE="_gcc"' '-DPYBIND11_STDLIB="_libstdcpp"' '-DPYBIND11_BUILD_ABI="_cxxabi1011"' -DTORCH_EXTENSION_NAME=_ext -D_GLIBCXX_USE_CXX11_ABI=0 -gencode=arch=compute_70,code=compute_70 -gencode=arch=compute_70,code=sm_70
    ninja: build stopped: subcommand failed.
    Traceback (most recent call last):
      File "/usr/local/lib/python3.8/dist-packages/torch/utils/cpp_extension.py", line 2105, in _run_ninja_build
        subprocess.run(
      File "/usr/lib/python3.8/subprocess.py", line 516, in run
        raise CalledProcessError(retcode, process.args,
    subprocess.CalledProcessError: Command '['ninja', '-v', '-j', '79']' returned non-zero exit status 1.
 
    The above exception was the direct cause of the following exception:
 
    Traceback (most recent call last):
      File "<string>", line 2, in <module>
      File "<pip-setuptools-caller>", line 34, in <module>
      File "/workspace/Bench2DriveZoo/setup.py", line 181, in <module>
        setup(
      File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/lib/python3/dist-packages/setuptools/command/develop.py", line 34, in run
        self.install_for_development()
      File "/usr/lib/python3/dist-packages/setuptools/command/develop.py", line 114, in install_for_development
        self.run_command('build_ext')
      File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/lib/python3/dist-packages/setuptools/command/build_ext.py", line 79, in run
        _build_ext.run(self)
      File "/usr/lib/python3.8/distutils/command/build_ext.py", line 340, in run
        self.build_extensions()
      File "/usr/local/lib/python3.8/dist-packages/torch/utils/cpp_extension.py", line 866, in build_extensions
        build_ext.build_extensions(self)
      File "/usr/lib/python3.8/distutils/command/build_ext.py", line 449, in build_extensions
        self._build_extensions_serial()
      File "/usr/lib/python3.8/distutils/command/build_ext.py", line 474, in _build_extensions_serial
        self.build_extension(ext)
      File "/usr/lib/python3/dist-packages/setuptools/command/build_ext.py", line 202, in build_extension
        _build_ext.build_extension(self, ext)
      File "/home/vscode/.local/lib/python3.8/site-packages/Cython/Distutils/build_ext.py", line 135, in build_extension
        super(build_ext, self).build_extension(ext)
      File "/usr/lib/python3.8/distutils/command/build_ext.py", line 528, in build_extension
        objects = self.compiler.compile(sources,
      File "/usr/local/lib/python3.8/dist-packages/torch/utils/cpp_extension.py", line 679, in unix_wrap_ninja_compile
        _write_ninja_file_and_compile_objects(
      File "/usr/local/lib/python3.8/dist-packages/torch/utils/cpp_extension.py", line 1785, in _write_ninja_file_and_compile_objects
        _run_ninja_build(
      File "/usr/local/lib/python3.8/dist-packages/torch/utils/cpp_extension.py", line 2121, in _run_ninja_build
        raise RuntimeError(message) from e
    RuntimeError: Error compiling objects for extension
    error: subprocess-exited-with-error
   
    × python setup.py develop did not run successfully.
    │ exit code: 1
    ╰─> See above for output.
   
    note: This error originates from a subprocess, and is likely not a problem with pip.
    full command: /usr/bin/python3.8 -c '
    exec(compile('"'"''"'"''"'"'
    # This is <pip-setuptools-caller> -- a caller that pip uses to run setup.py
    #
    # - It imports setuptools before invoking setup.py, to enable projects that directly
    #   import from `distutils.core` to work with newer packaging standards.
    # - It provides a clear error message when setuptools is not installed.
    # - It sets `sys.argv[0]` to the underlying `setup.py`, when invoking `setup.py` so
    #   setuptools doesn'"'"'t think the script is `-c`. This avoids the following warning:
    #     manifest_maker: standard file '"'"'-c'"'"' not found".
    # - It generates a shim setup.py, for handling setup.cfg-only projects.
    import os, sys, tokenize
   
    try:
        import setuptools
    except ImportError as error:
        print(
            "ERROR: Can not execute `setup.py` since setuptools is not available in "
            "the build environment.",
            file=sys.stderr,
        )
        sys.exit(1)
   
    __file__ = %r
    sys.argv[0] = __file__
   
    if os.path.exists(__file__):
        filename = __file__
        with tokenize.open(__file__) as f:
            setup_py_code = f.read()
    else:
        filename = "<auto-generated setuptools caller>"
        setup_py_code = "from setuptools import setup; setup()"
   
    exec(compile(setup_py_code, filename, "exec"))
    '"'"''"'"''"'"' % ('"'"'/workspace/Bench2DriveZoo/setup.py'"'"',), "<pip-setuptools-caller>", "exec"))' develop --no-deps --user --prefix=
    cwd: /workspace/Bench2DriveZoo/
error: subprocess-exited-with-error
 
× python setup.py develop did not run successfully.
│ exit code: 1
╰─> See above for output.
 
note: This error originates from a subprocess, and is likely not a problem with pip.
```

**Comment by jayyoung0802** [comment]
Hi, the gcc/g++ version needs 9.4.0, and please check the "/usr/local/cuda/bin/nvcc -V" (CUDA 11.8).
