### ISSUE TITLE
It crashed when training the vad.

### ISSUE THREAD

**Issue by MandyMo** [Thinklab-SJTU/Bench2DriveZoo#25]
as indicated by the title, and the log are listed bellow,

KeyError: Caught KeyError in DataLoader worker process 4.
Original Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/_utils/fetch.py", line 58, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/usr/local/lib/python3.8/dist-packages/torch/utils/data/_utils/fetch.py", line 58, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/nvme_17t/project/e2e/mmcv/datasets/B2D_vad_dataset.py", line 361, in __getitem__
    data = self.prepare_train_data(idx)
  File "/nvme_17t/project/e2e/mmcv/datasets/B2D_vad_dataset.py", line 92, in prepare_train_data
    gt_labels,gt_bboxes = self.get_map_info(index)
  File "/nvme_17t/project/e2e/mmcv/datasets/B2D_vad_dataset.py", line 253, in get_map_info
    map_info = self.map_infos[town_name]
KeyError: 'Junction'

I really do not know what happened...

**Comment by zhiyuanzzz** [comment]
It seems that you are using an old version of our data. We changed the name of some routes in the new version. You may solve the problem by replacing all "T_Junction" in route name with "TJunction".

**Comment by MandyMo** [comment]
data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/nvme_17t/project/e2e/mmcv/datasets/B2D_vad_dataset.py", line 361, in __getitem__
    data = self.prepare_train_data(idx)
  File "/nvme_17t/project/e2e/mmcv/datasets/B2D_vad_dataset.py", line 91, in prepare_train_data
    example = self.pipeline(input_dict)
  File "/nvme_17t/project/e2e/mmcv/datasets/pipelines/compose.py", line 40, in __call__
    data = t(data)
  File "/nvme_17t/project/e2e/mmcv/datasets/pipelines/formating.py", line 683, in __call__
    results = super(VADFormatBundle3D, self).__call__(results)
  File "/nvme_17t/project/e2e/mmcv/datasets/pipelines/formating.py", line 605, in __call__
    results['gt_labels'] = np.array([
  File "/nvme_17t/project/e2e/mmcv/datasets/pipelines/formating.py", line 606, in <listcomp>
    self.class_names.index(n) for n in results['gt_names']
ValueError: 'walker.pedestrian.0042' is not in list

another crash....

**Comment by zhiyuanzzz** [comment]
@MandyMo Thanks for your question! We have updated configs, for VAD we updated `NameMapping`  in https://github.com/Thinklab-SJTU/Bench2DriveZoo/blob/uniad/vad/adzoo/vad/configs/VAD/VAD_base_e2e_b2d.py. Please git pull latest branch.
