### ISSUE TITLE
Can not reproduce UnIAD open-loop evaluation results

### ISSUE THREAD

**Issue by huangzehao** [Thinklab-SJTU/Bench2DriveZoo#35]
### Env
```
torch                     2.4.0+cu118
torchaudio                2.4.0+cu118
torchmetrics              0.11.4
torchvision               0.19.0+cu118
```

### Command Used
```
./adzoo/uniad/uniad_dist_eval.sh ./adzoo/uniad/configs/stage2_e2e/base_e2e_b2d.py ckpts/uniad_base_b2d.pth 8
```

### Results
```
mAP: 0.1247
mATE: 0.5209
mASE: 0.1685
mAOE: 0.0967
mAVE: 1.0649
NDS: 0.3152

Per-class results:
Object Class    AP      ATE     ASE     AOE     AVE
car     0.078   0.478   0.104   0.051   1.742
van     0.103   0.529   0.171   0.289   0.187
truck   0.049   0.551   0.463   0.065   5.117
bicycle 0.155   0.396   0.086   0.041   0.970
traffic_sign    0.140   0.599   0.061   0.060   0.019
traffic_cone    0.178   0.617   0.279   0.161   0.126
traffic_light   0.132   0.306   0.135   0.055   0.014
pedestrian      0.162   0.690   0.050   0.053   0.344
+-------------+--------+--------+--------+--------+--------+--------+
|   metrics   |  0.5s  |  1.0s  |  1.5s  |  2.0s  |  2.5s  |  3.0s  |
+-------------+--------+--------+--------+--------+--------+--------+
|   obj_col   | 0.0000 | 0.0006 | 0.0017 | 0.0104 | 0.0217 | 0.0308 |
| obj_box_col | 0.0028 | 0.0080 | 0.0168 | 0.0387 | 0.0563 | 0.0792 |
|      L2     | 0.2468 | 0.5228 | 0.8797 | 1.2687 | 1.6967 | 2.1447 |
+-------------+--------+--------+--------+--------+--------+--------+
```

### Note
I initially received an AssertionError.  To resolve this, I set eval_occ to False in [this line](https://github.com/Thinklab-SJTU/Bench2DriveZoo/blob/uniad/vad/adzoo/uniad/test_utils.py#L106).

The original error was
```
[rank1]: Traceback (most recent call last):                                                                           
[rank1]:   File "./adzoo/uniad/test.py", line 145, in <module>                                                        
[rank1]:     main()                                                                                                   
[rank1]:   File "./adzoo/uniad/test.py", line 124, in main                                                            
[rank1]:     outputs = custom_multi_gpu_test(model, data_loader, args.tmpdir, args.gpu_collect)
[rank1]:   File "Bench2DriveZoo/adzoo/uniad/test_utils.py", line 11
5, in custom_multi_gpu_test                                                                                           
[rank1]:     panoptic_metrics[key](result[0]['occ']['ins_seg_out'][..., limits, limits].contiguous().detach(),        
[rank1]:   File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1553, in _wrapped_call_impl
[rank1]:     return self._call_impl(*args, **kwargs)                                                                  
[rank1]:   File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1562, in _call_impl         
[rank1]:     return forward_call(*args, **kwargs)                                                                     
[rank1]:   File "/usr/local/lib/python3.8/dist-packages/torchmetrics/metric.py", line 234, in forward                
[rank1]:     self._forward_cache = self._forward_full_state_update(*args, **kwargs)                                   
[rank1]:   File "/usr/local/lib/python3.8/dist-packages/torchmetrics/metric.py", line 247, in _forward_full_state_upda
te                                                                                                                    
[rank1]:     self.update(*args, **kwargs)                                                                             
[rank1]:   File "/usr/local/lib/python3.8/dist-packages/torchmetrics/metric.py", line 390, in wrapped_func            
[rank1]:     update(*args, **kwargs)                                                                                  
[rank1]:   File "Bench2DriveZoo/mmcv/models/dense_heads/occ_head_pl
ugin/metrics.py", line 111, in update                                                                                 
[rank1]:     result = self.panoptic_metrics(                                                                          
[rank1]:   File "Bench2DriveZoo/mmcv/models/dense_heads/occ_head_pl
ugin/metrics.py", line 156, in panoptic_metrics                                                                       
[rank1]:     assert pred_segmentation.dim() == 2
```
### Questions
As shown in the reported result https://github.com/Thinklab-SJTU/Bench2DriveZoo?tab=readme-ov-file#uniad-and-vad, UniAD-Base achieve 0.73 L2(m) 2s . However, the reproduced result is 1.2687 L2(m) 2s. Are there any missing details during the inference?

**Comment by zhiyuanzzz** [comment]
1.The definition of planning L2 the code output is different from that reported in paper. There is a note at the end of [doc](https://github.com/Thinklab-SJTU/Bench2DriveZoo/blob/uniad/vad/docs/TRAIN_EVAL.md).
2.We use one GPU to eval. Different number of GPUs may lead to slightly different result.

**Comment by huangzehao** [comment]
Thanks for you reply. 
What about training? Can we train UniAD or VAD with multiple gpus? As shown in https://github.com/Thinklab-SJTU/Bench2DriveZoo/blob/uniad/vad/docs/TRAIN_EVAL.md#train-1, the VAD model is trained with a single GPU.

**Comment by zhiyuanzzz** [comment]
Yes. We use 8 gpus to train them actually. The slight difference in evaluation is caused by `video_test_mode` of the model. [Reference1](https://github.com/fundamentalvision/BEVFormer/blob/master/docs/getting_started.md) [Reference2](https://github.com/hustvl/VAD/blob/main/docs/train_eval.md). There is no such problem in training.
