### ISSUE TITLE
An error occurred during VAD training.

### ISSUE THREAD

**Issue by YiHuang108** [Thinklab-SJTU/Bench2DriveZoo#9]
I can train the VAD model and then save checkpoint.  However,  after that I cannot find img_metas[0][0]['scene_token']: in the Bench2DriveZoo/mmcv/models/detectors/VAD.py file. When I adjust the index to load'scene_token' correctly it shows File "/Bench2DriveZoo/mmcv/models/modules/VAD_transformer.py", line 232, in <listcomp> for each in kwargs['img_metas']]) again
TypeError: string indices must be integers

I wonder if it's my own fault. If not, will you do any further tinkering with the file? Thank you very much for your reply.

**Comment by jiaxiaosong1002** [comment]
@YiHuang108  Please provide more context information and error information.  We could not understand the error based on current description.

**Comment by YiHuang108** [comment]
I'm sorry I didn't make myself clear.  I can, of course, run the training file like this:

```
INFO:0.0.1:Epoch [1][500/544]   lr: 3.550e-06, eta: 0:01:08, time: 1.538, data_time: 0.037, memory: 16277, loss_cls: 0.6816, loss_bbox: 0.9283, loss_traj: 0.9720, loss_traj_cls: 0.0985, loss_map_cls: 0.4126, loss_map_bbox: 0.0000, loss_map_iou: 0.0000, loss_map_pts: 2.1340, loss_map_dir: 0.0508, loss_plan_reg: 0.1304, loss_plan_bound: 0.0000, loss_plan_col: 0.0000, loss_plan_dir: 0.0000, d0.loss_cls: 0.4609, d0.loss_bbox: 0.9735, d1.loss_cls: 0.4916, d1.loss_bbox: 0.9353, d2.loss_cls: 0.5646, d2.loss_bbox: 0.9310, d3.loss_cls: 0.6208, d3.loss_bbox: 0.9257, d4.loss_cls: 0.6563, d4.loss_bbox: 0.9311, d0.loss_map_cls: 0.2913, d0.loss_map_bbox: 0.0000, d0.loss_map_iou: 0.0000, d0.loss_map_pts: 2.6716, d0.loss_map_dir: 0.0512, d1.loss_map_cls: 0.3216, d1.loss_map_bbox: 0.0000, d1.loss_map_iou: 0.0000, d1.loss_map_pts: 2.3292, d1.loss_map_dir: 0.0508, d2.loss_map_cls: 0.3657, d2.loss_map_bbox: 0.0000, d2.loss_map_iou: 0.0000, d2.loss_map_pts: 2.2001, d2.loss_map_dir: 0.0508, d3.loss_map_cls: 0.3908, d3.loss_map_bbox: 0.0000, d3.loss_map_iou: 0.0000, d3.loss_map_pts: 2.1567, d3.loss_map_dir: 0.0508, d4.loss_map_cls: 0.4051, d4.loss_map_bbox: 0.0000, d4.loss_map_iou: 0.0000, d4.loss_map_pts: 2.1399, d4.loss_map_dir: 0.0508, loss: 26.4253, grad_norm: 47.2076
2024-07-05 09:46:34,406 - 0.0.1 - INFO - Saving checkpoint at 1 epochs
INFO:0.0.1:Saving checkpoint at 1 epochs
```


However, after that, it results in a "key error: scene_token" in the file "Bench2DriveZoo/mmcv/models/detectors/VAD.py," specifically in the following line:
`if img_metas[0][0][scene_token] != self.prev_frame_info['scenario_token']:`

In the print output, img_metas[0][0] does not contain ['scenario_token'], but img_metas[0]['scenario_token'] does exist and shows like this:
```
img_metas[0]['scene_token']:
 v1/ConstructionObstacleTwoWays_Town12_Route1091_Weather12
```
Come to the next step, it will return:
```

[                                                  ] 0/1088, elapsed: 0s, ETA:Traceback (most recent call last):
  File "./adzoo/vad/train.py", line 228, in <module>
    main()
  File "./adzoo/vad/train.py", line 224, in main
    meta=meta)
  File "Bench2DriveZoo/adzoo/bevformer/mmdet3d_plugin/bevformer/apis/train.py", line 33, in custom_train_model
    meta=meta)
  File "Bench2DriveZoo/adzoo/bevformer/mmdet3d_plugin/bevformer/apis/mmdet_train.py", line 202, in custom_train_detector
    runner.run(data_loaders, cfg.workflow)
  File "Bench2DriveZoo/mmcv/runner/epoch_based_runner.py", line 129, in run
    epoch_runner(data_loaders[i], **kwargs)
  File "Bench2DriveZoo/mmcv/runner/epoch_based_runner.py", line 55, in train
    self.call_hook('after_train_epoch')
  File "Bench2DriveZoo/mmcv/runner/base_runner.py", line 297, in call_hook
    getattr(hook, fn_name)(self)
  File "Bench2DriveZoo/mmcv/runner/hooks/evaluation.py", line 266, in after_train_epoch
    self._do_evaluate(runner)
  File "Bench2DriveZoo/mmcv/core/evaluation/eval_hooks.py", line 125, in _do_evaluate
    gpu_collect=self.gpu_collect)
  File "Bench2DriveZoo/adzoo/bevformer/apis/test.py", line 71, in custom_multi_gpu_test
    result = model(data, return_loss=False, rescale=True)
  File "miniconda3/envs/pyhy/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "miniconda3/envs/pyhy/lib/python3.7/site-packages/torch/nn/parallel/distributed.py", line 886, in forward
    output = self.module(*inputs[0], **kwargs[0])
  File "miniconda3/envs/pyhy/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "Bench2DriveZoo/mmcv/models/detectors/VAD.py", line 194, in forward
    outputs = self.forward_test(**inputs, rescale=rescale)
  File "Bench2DriveZoo/mmcv/models/detectors/VAD.py", line 377, in forward_test
    **kwargs
  File "Bench2DriveZoo/mmcv/models/detectors/VAD.py", line 440, in simple_test
    gt_attr_labels=gt_attr_labels,
  File "Bench2DriveZoo/mmcv/models/detectors/VAD.py", line 493, in simple_test_pts
    outs = self.pts_bbox_head(x, img_metas, prev_bev=prev_bev, ego_his_trajs=ego_his_trajs, ego_lcf_feat=ego_lcf_feat)
  File "miniconda3/envs/pyhy/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "Bench2DriveZoo/mmcv/utils/fp16_utils.py", line 185, in new_func
    return old_func(*args, **kwargs)
  File "Bench2DriveZoo/mmcv/models/dense_heads/VAD_head.py", line 551, in forward
    prev_bev=prev_bev
  File "miniconda3/envs/pyhy/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "Bench2DriveZoo/mmcv/models/modules/VAD_transformer.py", line 372, in forward
    **kwargs)  # bev_embed shape: bs, bev_h*bev_w, embed_dims
  File "Bench2DriveZoo/mmcv/models/modules/VAD_transformer.py", line 232, in get_bev_features
    for each in kwargs['img_metas']])
  File "Bench2DriveZoo/mmcv/models/modules/VAD_transformer.py", line 232, in <listcomp>
    for each in kwargs['img_metas']])
TypeError: string indices must be integers

```

**Comment by YiHuang108** [comment]
I found that if I use the test script directly after using the train script, it works. I wonder if the train script connects to the test part by default, but this part is incorrect. I didn't understand where shows this part of the code. I would appreciate it if you could explain.

**Comment by zhiyuanzzz** [comment]
@YiHuang108 Hi, thanks for your question! This is beacuse a wrong pipline is used in evaluation. We have fixed that, please git pull latest branch.

**Comment by YiHuang108** [comment]
Thanks very much
